# Uncomment this line to define a global platform for your project
 platform :ios, '8.0'

target 'FindStations' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FindStations
  pod 'Alamofire', '~> 3.5'
  pod 'SwiftyJSON', '~> 2.3'

end
